[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#1877F2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#1C1E21"
font = "sans serif"

[browser]
gatherUsageStats = false
